[2023-03-30T04:17:39.710+0000] {processor.py:153} INFO - Started process (PID=178) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:17:39.711+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:17:39.712+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:17:39.712+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:17:40.470+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:17:40.469+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:17:40.470+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:17:40.484+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.777 seconds
[2023-03-30T04:18:10.683+0000] {processor.py:153} INFO - Started process (PID=257) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:18:10.694+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:18:10.695+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:18:10.695+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:18:10.883+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:18:10.882+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:18:10.884+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:18:10.900+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.219 seconds
[2023-03-30T04:18:41.107+0000] {processor.py:153} INFO - Started process (PID=311) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:18:41.118+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:18:41.119+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:18:41.119+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:18:41.320+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:18:41.317+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:18:41.320+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:18:41.338+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.234 seconds
[2023-03-30T04:19:11.533+0000] {processor.py:153} INFO - Started process (PID=389) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:19:11.544+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:19:11.545+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:19:11.545+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:19:11.752+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:19:11.749+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:19:11.752+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:19:11.780+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.249 seconds
[2023-03-30T04:19:41.975+0000] {processor.py:153} INFO - Started process (PID=443) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:19:41.986+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:19:41.987+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:19:41.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:19:42.195+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:19:42.193+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:19:42.195+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:19:42.225+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.252 seconds
[2023-03-30T04:20:12.423+0000] {processor.py:153} INFO - Started process (PID=521) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:20:12.424+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:20:12.426+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:20:12.425+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:20:12.684+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:20:12.682+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:20:12.684+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:20:12.707+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.292 seconds
[2023-03-30T04:20:42.954+0000] {processor.py:153} INFO - Started process (PID=575) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:20:42.955+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:20:42.956+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:20:42.956+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:20:43.211+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:20:43.209+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:20:43.211+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:20:43.227+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.276 seconds
[2023-03-30T04:21:13.396+0000] {processor.py:153} INFO - Started process (PID=653) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:21:13.404+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:21:13.405+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:21:13.405+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:21:13.612+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:21:13.610+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:21:13.612+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:21:13.628+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.235 seconds
[2023-03-30T04:21:43.812+0000] {processor.py:153} INFO - Started process (PID=707) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:21:43.823+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:21:43.825+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:21:43.824+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:21:44.067+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:21:44.065+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:21:44.068+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:21:44.088+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.279 seconds
[2023-03-30T04:22:14.289+0000] {processor.py:153} INFO - Started process (PID=785) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:22:14.300+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:22:14.301+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:22:14.301+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:22:14.516+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:22:14.514+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:22:14.517+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:22:14.535+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.248 seconds
[2023-03-30T04:22:44.775+0000] {processor.py:153} INFO - Started process (PID=839) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:22:44.776+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:22:44.777+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:22:44.777+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:22:45.004+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:22:45.002+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:22:45.005+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:22:45.036+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.264 seconds
[2023-03-30T04:23:15.227+0000] {processor.py:153} INFO - Started process (PID=917) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:23:15.228+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:23:15.229+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:23:15.228+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:23:15.431+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:23:15.428+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:23:15.431+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:23:15.460+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.236 seconds
[2023-03-30T04:23:45.660+0000] {processor.py:153} INFO - Started process (PID=971) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:23:45.671+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:23:45.672+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:23:45.672+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:23:45.899+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:23:45.896+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:23:45.900+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:23:45.933+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.276 seconds
[2023-03-30T04:24:16.125+0000] {processor.py:153} INFO - Started process (PID=1049) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:24:16.136+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:24:16.137+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:24:16.137+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:24:16.345+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:24:16.343+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:24:16.345+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:24:16.360+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.237 seconds
[2023-03-30T04:24:46.546+0000] {processor.py:153} INFO - Started process (PID=1103) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:24:46.547+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:24:46.548+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:24:46.548+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:24:46.769+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:24:46.766+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:24:46.769+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:24:46.800+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.257 seconds
[2023-03-30T04:25:16.991+0000] {processor.py:153} INFO - Started process (PID=1180) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:25:17.002+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:25:17.003+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:25:17.003+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:25:17.212+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:25:17.210+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:25:17.213+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:25:17.240+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.251 seconds
[2023-03-30T04:25:47.418+0000] {processor.py:153} INFO - Started process (PID=1234) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:25:47.419+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:25:47.420+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:25:47.420+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:25:47.609+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:25:47.607+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:25:47.609+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:25:47.635+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.218 seconds
[2023-03-30T04:26:17.804+0000] {processor.py:153} INFO - Started process (PID=1312) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:26:17.805+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:26:17.805+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:26:17.805+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:26:18.009+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:26:18.008+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:26:18.010+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:26:18.027+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.225 seconds
[2023-03-30T04:26:48.213+0000] {processor.py:153} INFO - Started process (PID=1366) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:26:48.224+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:26:48.226+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:26:48.225+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:26:48.449+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:26:48.447+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:26:48.449+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:26:48.478+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.267 seconds
[2023-03-30T04:27:18.656+0000] {processor.py:153} INFO - Started process (PID=1444) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:27:18.666+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:27:18.667+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:27:18.667+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:27:18.860+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:27:18.859+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:27:18.861+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:27:18.888+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.235 seconds
[2023-03-30T04:27:49.062+0000] {processor.py:153} INFO - Started process (PID=1498) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:27:49.073+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:27:49.074+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:27:49.074+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:27:49.292+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:27:49.290+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:27:49.293+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:27:49.322+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.263 seconds
[2023-03-30T04:28:19.507+0000] {processor.py:153} INFO - Started process (PID=1576) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:28:19.517+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:28:19.518+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:28:19.518+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:28:19.720+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:28:19.718+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:28:19.721+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:28:19.741+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.236 seconds
[2023-03-30T04:28:49.938+0000] {processor.py:153} INFO - Started process (PID=1630) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:28:49.939+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:28:49.939+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:28:49.939+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:28:50.181+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:28:50.179+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:28:50.181+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:28:50.211+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.276 seconds
[2023-03-30T04:29:20.404+0000] {processor.py:153} INFO - Started process (PID=1708) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:29:20.415+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:29:20.416+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:29:20.415+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:29:20.616+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:29:20.615+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:29:20.617+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:29:20.638+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.236 seconds
[2023-03-30T04:29:50.833+0000] {processor.py:153} INFO - Started process (PID=1762) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:29:50.844+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:29:50.844+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:29:50.844+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:29:51.051+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:29:51.049+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:29:51.051+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:29:51.086+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.256 seconds
[2023-03-30T04:30:21.276+0000] {processor.py:153} INFO - Started process (PID=1840) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:30:21.277+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:30:21.278+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:30:21.277+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:30:21.450+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:30:21.448+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2023-03-30T04:30:21.451+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:30:21.466+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.191 seconds
[2023-03-30T04:33:04.997+0000] {processor.py:153} INFO - Started process (PID=208) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:33:04.998+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:33:04.999+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:33:04.999+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:33:05.906+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:33:05.905+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 3, in <module>
    def get_mongo_db(institute:str)-> pymongo.MongoClient.database:
AttributeError: type object 'MongoClient' has no attribute 'database'
[2023-03-30T04:33:05.906+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:33:05.930+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.936 seconds
[2023-03-30T04:33:36.113+0000] {processor.py:153} INFO - Started process (PID=287) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:33:36.124+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:33:36.125+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:33:36.125+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:33:36.353+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:33:36.352+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 3, in <module>
    def get_mongo_db(institute:str)-> pymongo.MongoClient.database:
AttributeError: type object 'MongoClient' has no attribute 'database'
[2023-03-30T04:33:36.354+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:33:36.369+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.258 seconds
[2023-03-30T04:34:06.558+0000] {processor.py:153} INFO - Started process (PID=341) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:34:06.569+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:34:06.570+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:34:06.570+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:34:06.873+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:34:06.872+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 3, in <module>
    def get_mongo_db(institute:str)-> pymongo.MongoClient.database:
AttributeError: type object 'MongoClient' has no attribute 'database'
[2023-03-30T04:34:06.873+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:34:06.899+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.345 seconds
[2023-03-30T04:34:37.061+0000] {processor.py:153} INFO - Started process (PID=419) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:34:37.062+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:34:37.063+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:34:37.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:34:37.332+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:34:37.330+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 7, in <module>
    from etl.extraction.UFRN import *
  File "/opt/airflow/dags/etl/extraction/UFRN.py", line 5, in <module>
    from etl.utils.mongo import get_mongo_db, insert_many, drop_collection
  File "/opt/airflow/dags/etl/utils/mongo.py", line 9, in <module>
    def insert_many(database: pymongo.MongoClient.database, collection_name: str, data: list) -> dict:
AttributeError: type object 'MongoClient' has no attribute 'database'
[2023-03-30T04:34:37.332+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:34:37.351+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.293 seconds
[2023-03-30T04:35:07.524+0000] {processor.py:153} INFO - Started process (PID=473) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:35:07.525+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:35:07.525+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:35:07.525+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:35:07.744+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:35:07.743+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 29, in <module>
    python_callable=drop_collection('ufrn','docentes'),
  File "/opt/airflow/dags/etl/utils/mongo.py", line 25, in drop_collection
    collection = database.get_collection(collection_name)
AttributeError: 'str' object has no attribute 'get_collection'
[2023-03-30T04:35:07.744+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:35:07.766+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.244 seconds
[2023-03-30T04:35:37.927+0000] {processor.py:153} INFO - Started process (PID=551) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:35:37.938+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:35:37.938+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:35:37.938+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:35:38.168+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:35:38.167+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 29, in <module>
    python_callable=drop_collection('ufrn','docentes'),
  File "/opt/airflow/dags/etl/utils/mongo.py", line 25, in drop_collection
    collection = database.get_collection(collection_name)
AttributeError: 'str' object has no attribute 'get_collection'
[2023-03-30T04:35:38.168+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:35:38.186+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.261 seconds
[2023-03-30T04:36:08.365+0000] {processor.py:153} INFO - Started process (PID=605) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:36:08.376+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:36:08.377+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:36:08.377+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:36:08.610+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:36:08.609+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 29, in <module>
    python_callable=drop_collection('ufrn','docentes'),
  File "/opt/airflow/dags/etl/utils/mongo.py", line 25, in drop_collection
    collection = database.get_collection(collection_name)
AttributeError: 'str' object has no attribute 'get_collection'
[2023-03-30T04:36:08.610+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:36:08.636+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.274 seconds
[2023-03-30T04:36:38.808+0000] {processor.py:153} INFO - Started process (PID=668) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:36:38.808+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:36:38.809+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:36:38.809+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:36:39.055+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:36:39.054+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 29, in <module>
    python_callable=drop_collection('ufrn','docentes'),
  File "/opt/airflow/dags/etl/utils/mongo.py", line 25, in drop_collection
    collection = database.get_collection(collection_name)
AttributeError: 'str' object has no attribute 'get_collection'
[2023-03-30T04:36:39.055+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:36:39.083+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.278 seconds
[2023-03-30T04:36:45.162+0000] {processor.py:153} INFO - Started process (PID=689) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:36:45.173+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:36:45.174+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:36:45.173+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:36:45.428+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:36:45.428+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 29, in <module>
    python_callable=drop_collection('ufrn','docentes'),
  File "/opt/airflow/dags/etl/utils/mongo.py", line 25, in drop_collection
    collection = database.get_collection(collection_name)
AttributeError: 'str' object has no attribute 'get_collection'
[2023-03-30T04:36:45.429+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:36:45.444+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.284 seconds
[2023-03-30T04:37:15.619+0000] {processor.py:153} INFO - Started process (PID=752) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:37:15.620+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:37:15.621+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:37:15.621+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:37:15.908+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:37:15.906+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 29, in <module>
    python_callable=drop_collection('ufrn','docentes'),
  File "/opt/airflow/dags/etl/utils/mongo.py", line 25, in drop_collection
    collection = database.get_collection(collection_name)
AttributeError: 'str' object has no attribute 'get_collection'
[2023-03-30T04:37:15.908+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:37:15.943+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.326 seconds
[2023-03-30T04:37:46.133+0000] {processor.py:153} INFO - Started process (PID=821) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:37:46.144+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:37:46.145+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:37:46.145+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:37:46.383+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:37:46.382+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 29, in <module>
    python_callable=drop_collection('ufrn','docentes'),
  File "/opt/airflow/dags/etl/utils/mongo.py", line 25, in drop_collection
    collection = database.get_collection(collection_name)
AttributeError: 'str' object has no attribute 'get_collection'
[2023-03-30T04:37:46.383+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:37:46.413+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.283 seconds
[2023-03-30T04:38:16.599+0000] {processor.py:153} INFO - Started process (PID=884) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:38:16.610+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:38:16.611+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:38:16.611+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:38:16.980+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:38:16.979+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 29, in <module>
    python_callable=drop_collection('ufrn','docentes'),
  File "/opt/airflow/dags/etl/utils/mongo.py", line 25, in drop_collection
    collection = database.get_collection(collection_name)
AttributeError: 'str' object has no attribute 'get_collection'
[2023-03-30T04:38:16.981+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:38:17.017+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.421 seconds
[2023-03-30T04:38:47.208+0000] {processor.py:153} INFO - Started process (PID=953) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:38:47.219+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:38:47.220+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:38:47.220+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:38:47.467+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:38:47.466+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 29, in <module>
    python_callable=drop_collection('ufrn','docentes'),
  File "/opt/airflow/dags/etl/utils/mongo.py", line 25, in drop_collection
    collection = database.get_collection(collection_name)
AttributeError: 'str' object has no attribute 'get_collection'
[2023-03-30T04:38:47.467+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:38:47.500+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.294 seconds
[2023-03-30T04:39:17.692+0000] {processor.py:153} INFO - Started process (PID=1031) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:39:17.703+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:39:17.704+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:39:17.703+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:39:18.002+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:39:18.001+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 29, in <module>
    python_callable=drop_collection('ufrn','docentes'),
  File "/opt/airflow/dags/etl/utils/mongo.py", line 25, in drop_collection
    collection = database.get_collection(collection_name)
AttributeError: 'str' object has no attribute 'get_collection'
[2023-03-30T04:39:18.002+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:39:18.021+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.331 seconds
[2023-03-30T04:39:48.213+0000] {processor.py:153} INFO - Started process (PID=1085) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:39:48.214+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:39:48.214+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:39:48.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:39:48.421+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:39:48.420+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 29, in <module>
    python_callable=drop_collection('ufrn','docentes'),
  File "/opt/airflow/dags/etl/utils/mongo.py", line 25, in drop_collection
    collection = database.get_collection(collection_name)
AttributeError: 'str' object has no attribute 'get_collection'
[2023-03-30T04:39:48.421+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:39:48.447+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.236 seconds
[2023-03-30T04:40:18.626+0000] {processor.py:153} INFO - Started process (PID=1149) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:40:18.636+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:40:18.637+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:40:18.637+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:40:18.870+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:40:18.868+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 29, in <module>
    python_callable=drop_collection('ufrn','docentes'),
  File "/opt/airflow/dags/etl/utils/mongo.py", line 25, in drop_collection
    collection = database.get_collection(collection_name)
AttributeError: 'str' object has no attribute 'get_collection'
[2023-03-30T04:40:18.871+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:40:18.912+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.289 seconds
[2023-03-30T04:40:49.119+0000] {processor.py:153} INFO - Started process (PID=1218) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:40:49.130+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:40:49.132+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:40:49.131+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:40:49.393+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:40:49.392+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 29, in <module>
    python_callable=drop_collection('ufrn','docentes'),
  File "/opt/airflow/dags/etl/utils/mongo.py", line 25, in drop_collection
    collection = database.get_collection(collection_name)
AttributeError: 'str' object has no attribute 'get_collection'
[2023-03-30T04:40:49.394+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:40:49.440+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.324 seconds
[2023-03-30T04:40:51.142+0000] {processor.py:153} INFO - Started process (PID=1224) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:40:51.142+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:40:51.143+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:40:51.143+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:40:53.851+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:40:53.849+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 30, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-03-30T04:40:53.851+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:40:53.883+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 2.744 seconds
[2023-03-30T04:41:24.088+0000] {processor.py:153} INFO - Started process (PID=1309) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:41:24.099+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:41:24.100+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:41:24.100+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:41:28.696+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:41:28.694+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 30, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-03-30T04:41:28.696+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:41:28.716+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 4.630 seconds
[2023-03-30T04:41:58.876+0000] {processor.py:153} INFO - Started process (PID=1394) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:41:58.886+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:41:58.888+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:41:58.887+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:42:02.648+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:42:02.646+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 30, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-03-30T04:42:02.649+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:42:02.687+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 3.814 seconds
[2023-03-30T04:42:32.904+0000] {processor.py:153} INFO - Started process (PID=1464) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:42:32.905+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:42:32.905+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:42:32.905+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:42:37.000+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:42:36.998+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 30, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-03-30T04:42:37.001+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:42:37.027+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 4.127 seconds
[2023-03-30T04:43:07.138+0000] {processor.py:153} INFO - Started process (PID=1540) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:43:07.149+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:43:07.149+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:43:07.149+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:43:10.650+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:43:10.649+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 30, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-03-30T04:43:10.651+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:43:10.670+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 3.535 seconds
[2023-03-30T04:43:40.861+0000] {processor.py:153} INFO - Started process (PID=1625) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:43:40.862+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:43:40.862+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:43:40.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:43:44.679+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:43:44.676+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 30, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-03-30T04:43:44.680+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:43:44.705+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 3.847 seconds
[2023-03-30T04:44:14.902+0000] {processor.py:153} INFO - Started process (PID=1710) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:44:14.903+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:44:14.904+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:44:14.904+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:44:18.894+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:44:18.892+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 30, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-03-30T04:44:18.894+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:44:18.929+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 4.031 seconds
[2023-03-30T04:44:49.085+0000] {processor.py:153} INFO - Started process (PID=1795) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:44:49.086+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:44:49.086+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:44:49.086+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:44:51.861+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:44:51.858+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 30, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-03-30T04:44:51.862+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:44:51.899+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 2.817 seconds
[2023-03-30T04:44:54.957+0000] {processor.py:153} INFO - Started process (PID=1808) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:44:54.957+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:44:54.958+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:44:54.958+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:44:57.979+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:44:57.977+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 30, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-03-30T04:44:57.979+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:44:58.015+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 3.062 seconds
[2023-03-30T04:45:28.143+0000] {processor.py:153} INFO - Started process (PID=1893) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:45:28.144+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:45:28.144+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:45:28.144+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:45:31.034+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:45:31.031+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 30, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-03-30T04:45:31.034+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:45:31.065+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 2.926 seconds
[2023-03-30T04:46:01.280+0000] {processor.py:153} INFO - Started process (PID=1978) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:46:01.292+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:46:01.292+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:46:01.292+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:46:04.571+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:46:04.569+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 30, in <module>
    dag=dag,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-03-30T04:46:04.572+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:46:04.603+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 3.325 seconds
[2023-03-30T04:46:34.803+0000] {processor.py:153} INFO - Started process (PID=2040) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:46:34.814+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:46:34.815+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:46:34.815+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:46:35.079+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:46:35.078+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 29, in <module>
    python_callable=drop_from_ufrn_db('docentes'),
NameError: name 'drop_from_ufrn_db' is not defined
[2023-03-30T04:46:35.080+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:46:35.099+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.298 seconds
[2023-03-30T04:47:05.300+0000] {processor.py:153} INFO - Started process (PID=2118) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:47:05.311+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:47:05.312+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:47:05.312+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:47:05.547+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:47:05.546+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/ufrn_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ufrn_dag.py", line 29, in <module>
    python_callable=drop_from_ufrn_db('docentes'),
NameError: name 'drop_from_ufrn_db' is not defined
[2023-03-30T04:47:05.548+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:47:05.577+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.280 seconds
[2023-03-30T04:47:13.354+0000] {processor.py:153} INFO - Started process (PID=2133) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:47:13.365+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:47:13.366+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:47:13.365+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:47:13.767+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:47:13.837+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:47:13.836+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:47:13.860+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:47:13.860+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-28T00:00:00+00:00, run_after=2023-03-29T00:00:00+00:00
[2023-03-30T04:47:13.886+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.536 seconds
[2023-03-30T04:47:44.060+0000] {processor.py:153} INFO - Started process (PID=2343) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:47:44.061+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:47:44.062+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:47:44.062+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:47:44.343+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:47:44.376+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:47:44.376+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:47:44.411+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:47:44.411+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:47:44.447+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.389 seconds
[2023-03-30T04:48:14.632+0000] {processor.py:153} INFO - Started process (PID=2404) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:48:14.643+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:48:14.645+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:48:14.644+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:48:14.930+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:48:14.956+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:48:14.956+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:48:14.981+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:48:14.981+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:48:15.016+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.387 seconds
[2023-03-30T04:48:45.206+0000] {processor.py:153} INFO - Started process (PID=2475) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:48:45.217+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:48:45.218+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:48:45.218+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:48:45.449+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:48:45.475+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:48:45.474+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:48:45.499+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:48:45.499+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:48:45.532+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.328 seconds
[2023-03-30T04:49:15.731+0000] {processor.py:153} INFO - Started process (PID=2536) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:49:15.741+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:49:15.743+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:49:15.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:49:16.079+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:49:16.113+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:49:16.112+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:49:16.143+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:49:16.142+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:49:16.166+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.438 seconds
[2023-03-30T04:49:46.360+0000] {processor.py:153} INFO - Started process (PID=2607) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:49:46.371+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:49:46.371+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:49:46.371+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:49:46.607+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:49:46.634+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:49:46.633+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:49:46.662+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:49:46.661+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:49:46.693+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.335 seconds
[2023-03-30T04:50:16.887+0000] {processor.py:153} INFO - Started process (PID=2670) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:50:16.888+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:50:16.889+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:50:16.889+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:50:17.159+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:50:17.187+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:50:17.186+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:50:17.213+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:50:17.213+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:50:17.246+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.362 seconds
[2023-03-30T04:50:47.438+0000] {processor.py:153} INFO - Started process (PID=2739) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:50:47.439+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:50:47.439+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:50:47.439+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:50:47.765+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:50:47.788+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:50:47.788+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:50:47.810+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:50:47.810+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:50:47.832+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.396 seconds
[2023-03-30T04:51:17.994+0000] {processor.py:153} INFO - Started process (PID=2800) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:51:18.005+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:51:18.006+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:51:18.006+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:51:18.276+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:51:18.308+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:51:18.306+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:51:18.348+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:51:18.348+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:51:18.385+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.394 seconds
[2023-03-30T04:51:48.571+0000] {processor.py:153} INFO - Started process (PID=2871) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:51:48.581+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:51:48.582+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:51:48.582+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:51:48.808+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:51:48.835+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:51:48.834+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:51:48.860+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:51:48.860+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:51:48.893+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.326 seconds
[2023-03-30T04:52:19.092+0000] {processor.py:153} INFO - Started process (PID=2934) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:52:19.103+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:52:19.104+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:52:19.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:52:19.365+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:52:19.392+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:52:19.391+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:52:19.418+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:52:19.418+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:52:19.451+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.362 seconds
[2023-03-30T04:52:49.649+0000] {processor.py:153} INFO - Started process (PID=3003) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:52:49.660+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:52:49.662+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:52:49.661+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:52:49.910+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:52:49.936+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:52:49.936+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:52:49.963+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:52:49.963+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:52:49.983+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.337 seconds
[2023-03-30T04:53:20.176+0000] {processor.py:153} INFO - Started process (PID=3066) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:53:20.186+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:53:20.187+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:53:20.187+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:53:20.530+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:53:20.554+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:53:20.553+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:53:20.576+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:53:20.576+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:53:20.606+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.433 seconds
[2023-03-30T04:53:50.789+0000] {processor.py:153} INFO - Started process (PID=3135) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:53:50.800+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:53:50.801+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:53:50.801+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:53:51.037+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:53:51.065+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:53:51.064+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:53:51.089+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:53:51.089+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:53:51.110+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.323 seconds
[2023-03-30T04:54:21.299+0000] {processor.py:153} INFO - Started process (PID=3213) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:54:21.310+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:54:21.311+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:54:21.311+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:54:21.537+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:54:21.559+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:54:21.559+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:54:21.582+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:54:21.582+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:54:21.601+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.304 seconds
[2023-03-30T04:54:51.786+0000] {processor.py:153} INFO - Started process (PID=3267) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:54:51.797+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:54:51.798+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:54:51.798+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:54:52.065+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:54:52.087+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:54:52.086+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:54:52.107+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:54:52.107+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:54:52.125+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.342 seconds
[2023-03-30T04:55:22.314+0000] {processor.py:153} INFO - Started process (PID=3345) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:55:22.324+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:55:22.325+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:55:22.325+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:55:22.547+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:55:22.568+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:55:22.567+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:55:22.592+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:55:22.592+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:55:22.620+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.309 seconds
[2023-03-30T04:55:52.815+0000] {processor.py:153} INFO - Started process (PID=3399) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:55:52.816+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:55:52.817+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:55:52.817+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:55:53.073+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:55:53.100+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:55:53.099+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:55:53.127+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:55:53.127+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:55:53.159+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.346 seconds
[2023-03-30T04:56:23.337+0000] {processor.py:153} INFO - Started process (PID=3561) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:56:23.347+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:56:23.348+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:56:23.347+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:56:23.621+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:56:23.667+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:56:23.664+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:56:23.719+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:56:23.718+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:56:23.755+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.421 seconds
[2023-03-30T04:56:53.952+0000] {processor.py:153} INFO - Started process (PID=3631) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:56:53.962+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:56:53.963+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:56:53.963+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:56:54.205+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:56:54.232+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:56:54.231+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:56:54.254+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:56:54.254+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:56:54.273+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.324 seconds
[2023-03-30T04:57:24.457+0000] {processor.py:153} INFO - Started process (PID=3709) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:57:24.459+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:57:24.460+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:57:24.460+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:57:24.688+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:57:24.712+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:57:24.712+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:57:24.735+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:57:24.735+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:57:24.765+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.310 seconds
[2023-03-30T04:57:54.956+0000] {processor.py:153} INFO - Started process (PID=3763) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:57:54.966+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:57:54.968+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:57:54.967+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:57:55.247+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:57:55.276+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:57:55.276+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:57:55.306+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:57:55.306+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:57:55.342+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.390 seconds
[2023-03-30T04:58:25.527+0000] {processor.py:153} INFO - Started process (PID=3911) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:58:25.533+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:58:25.534+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:58:25.534+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:58:25.779+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:58:25.802+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:58:25.801+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:58:25.826+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:58:25.826+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:58:25.844+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.319 seconds
[2023-03-30T04:58:56.027+0000] {processor.py:153} INFO - Started process (PID=3978) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:58:56.028+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:58:56.028+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:58:56.028+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:58:56.229+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:58:56.249+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:58:56.248+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:58:56.269+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:58:56.269+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:58:56.284+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.258 seconds
[2023-03-30T04:59:26.463+0000] {processor.py:153} INFO - Started process (PID=4063) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:59:26.465+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:59:26.466+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:59:26.466+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:59:26.749+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:59:26.772+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:59:26.771+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:59:26.795+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:59:26.795+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:59:26.823+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.364 seconds
[2023-03-30T04:59:57.002+0000] {processor.py:153} INFO - Started process (PID=4147) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:59:57.012+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T04:59:57.013+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:59:57.013+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:59:57.264+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T04:59:57.286+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:59:57.286+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T04:59:57.308+0000] {logging_mixin.py:137} INFO - [2023-03-30T04:59:57.308+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T04:59:57.336+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.338 seconds
[2023-03-30T05:00:27.518+0000] {processor.py:153} INFO - Started process (PID=4225) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T05:00:27.519+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T05:00:27.520+0000] {logging_mixin.py:137} INFO - [2023-03-30T05:00:27.520+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T05:00:27.755+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T05:00:27.778+0000] {logging_mixin.py:137} INFO - [2023-03-30T05:00:27.777+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T05:00:27.801+0000] {logging_mixin.py:137} INFO - [2023-03-30T05:00:27.801+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T05:00:27.821+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.305 seconds
[2023-03-30T05:00:58.011+0000] {processor.py:153} INFO - Started process (PID=4279) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T05:00:58.021+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T05:00:58.022+0000] {logging_mixin.py:137} INFO - [2023-03-30T05:00:58.022+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T05:00:58.275+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T05:00:58.314+0000] {logging_mixin.py:137} INFO - [2023-03-30T05:00:58.313+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T05:00:58.341+0000] {logging_mixin.py:137} INFO - [2023-03-30T05:00:58.341+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T05:00:58.363+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.355 seconds
[2023-03-30T05:01:28.560+0000] {processor.py:153} INFO - Started process (PID=4357) to work on /opt/airflow/dags/ufrn_dag.py
[2023-03-30T05:01:28.570+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/ufrn_dag.py for tasks to queue
[2023-03-30T05:01:28.571+0000] {logging_mixin.py:137} INFO - [2023-03-30T05:01:28.571+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T05:01:28.792+0000] {processor.py:753} INFO - DAG(s) dict_keys(['ufrn_etl']) retrieved from /opt/airflow/dags/ufrn_dag.py
[2023-03-30T05:01:28.815+0000] {logging_mixin.py:137} INFO - [2023-03-30T05:01:28.814+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-03-30T05:01:28.838+0000] {logging_mixin.py:137} INFO - [2023-03-30T05:01:28.838+0000] {dag.py:3441} INFO - Setting next_dagrun for ufrn_etl to 2023-03-30T00:00:00+00:00, run_after=2023-03-31T00:00:00+00:00
[2023-03-30T05:01:28.869+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/ufrn_dag.py took 0.311 seconds
